// Code generated by protoc-gen-go.
// source: services.proto
// DO NOT EDIT!

/*
Package services is a generated protocol buffer package.

It is generated from these files:
	services.proto

It has these top-level messages:
	DrawRequest
	DrawResponse
	TextRequest
	TextResponse
	TimeFormat
	TimeResponse
*/
package services

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DrawRequest struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *DrawRequest) Reset()                    { *m = DrawRequest{} }
func (m *DrawRequest) String() string            { return proto.CompactTextString(m) }
func (*DrawRequest) ProtoMessage()               {}
func (*DrawRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DrawRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type DrawResponse struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *DrawResponse) Reset()                    { *m = DrawResponse{} }
func (m *DrawResponse) String() string            { return proto.CompactTextString(m) }
func (*DrawResponse) ProtoMessage()               {}
func (*DrawResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DrawResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DrawResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TextRequest struct {
	Text string `protobuf:"bytes,1,opt,name=text" json:"text,omitempty"`
	Font string `protobuf:"bytes,2,opt,name=font" json:"font,omitempty"`
}

func (m *TextRequest) Reset()                    { *m = TextRequest{} }
func (m *TextRequest) String() string            { return proto.CompactTextString(m) }
func (*TextRequest) ProtoMessage()               {}
func (*TextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TextRequest) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *TextRequest) GetFont() string {
	if m != nil {
		return m.Font
	}
	return ""
}

type TextResponse struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *TextResponse) Reset()                    { *m = TextResponse{} }
func (m *TextResponse) String() string            { return proto.CompactTextString(m) }
func (*TextResponse) ProtoMessage()               {}
func (*TextResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TextResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TextResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type TimeFormat struct {
	Format string `protobuf:"bytes,1,opt,name=format" json:"format,omitempty"`
	Font   string `protobuf:"bytes,2,opt,name=font" json:"font,omitempty"`
}

func (m *TimeFormat) Reset()                    { *m = TimeFormat{} }
func (m *TimeFormat) String() string            { return proto.CompactTextString(m) }
func (*TimeFormat) ProtoMessage()               {}
func (*TimeFormat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *TimeFormat) GetFormat() string {
	if m != nil {
		return m.Format
	}
	return ""
}

func (m *TimeFormat) GetFont() string {
	if m != nil {
		return m.Font
	}
	return ""
}

type TimeResponse struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *TimeResponse) Reset()                    { *m = TimeResponse{} }
func (m *TimeResponse) String() string            { return proto.CompactTextString(m) }
func (*TimeResponse) ProtoMessage()               {}
func (*TimeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *TimeResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TimeResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*DrawRequest)(nil), "services.DrawRequest")
	proto.RegisterType((*DrawResponse)(nil), "services.DrawResponse")
	proto.RegisterType((*TextRequest)(nil), "services.TextRequest")
	proto.RegisterType((*TextResponse)(nil), "services.TextResponse")
	proto.RegisterType((*TimeFormat)(nil), "services.TimeFormat")
	proto.RegisterType((*TimeResponse)(nil), "services.TimeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ImageSink service

type ImageSinkClient interface {
	Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error)
}

type imageSinkClient struct {
	cc *grpc.ClientConn
}

func NewImageSinkClient(cc *grpc.ClientConn) ImageSinkClient {
	return &imageSinkClient{cc}
}

func (c *imageSinkClient) Draw(ctx context.Context, in *DrawRequest, opts ...grpc.CallOption) (*DrawResponse, error) {
	out := new(DrawResponse)
	err := grpc.Invoke(ctx, "/services.ImageSink/Draw", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ImageSink service

type ImageSinkServer interface {
	Draw(context.Context, *DrawRequest) (*DrawResponse, error)
}

func RegisterImageSinkServer(s *grpc.Server, srv ImageSinkServer) {
	s.RegisterService(&_ImageSink_serviceDesc, srv)
}

func _ImageSink_Draw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrawRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImageSinkServer).Draw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.ImageSink/Draw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImageSinkServer).Draw(ctx, req.(*DrawRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ImageSink_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.ImageSink",
	HandlerType: (*ImageSinkServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Draw",
			Handler:    _ImageSink_Draw_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

// Client API for Textd service

type TextdClient interface {
	Write(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error)
}

type textdClient struct {
	cc *grpc.ClientConn
}

func NewTextdClient(cc *grpc.ClientConn) TextdClient {
	return &textdClient{cc}
}

func (c *textdClient) Write(ctx context.Context, in *TextRequest, opts ...grpc.CallOption) (*TextResponse, error) {
	out := new(TextResponse)
	err := grpc.Invoke(ctx, "/services.Textd/Write", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Textd service

type TextdServer interface {
	Write(context.Context, *TextRequest) (*TextResponse, error)
}

func RegisterTextdServer(s *grpc.Server, srv TextdServer) {
	s.RegisterService(&_Textd_serviceDesc, srv)
}

func _Textd_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TextdServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Textd/Write",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TextdServer).Write(ctx, req.(*TextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Textd_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Textd",
	HandlerType: (*TextdServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _Textd_Write_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

// Client API for Timed service

type TimedClient interface {
	Show(ctx context.Context, in *TimeFormat, opts ...grpc.CallOption) (*TimeResponse, error)
}

type timedClient struct {
	cc *grpc.ClientConn
}

func NewTimedClient(cc *grpc.ClientConn) TimedClient {
	return &timedClient{cc}
}

func (c *timedClient) Show(ctx context.Context, in *TimeFormat, opts ...grpc.CallOption) (*TimeResponse, error) {
	out := new(TimeResponse)
	err := grpc.Invoke(ctx, "/services.Timed/Show", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Timed service

type TimedServer interface {
	Show(context.Context, *TimeFormat) (*TimeResponse, error)
}

func RegisterTimedServer(s *grpc.Server, srv TimedServer) {
	s.RegisterService(&_Timed_serviceDesc, srv)
}

func _Timed_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeFormat)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TimedServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/services.Timed/Show",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TimedServer).Show(ctx, req.(*TimeFormat))
	}
	return interceptor(ctx, in, info, handler)
}

var _Timed_serviceDesc = grpc.ServiceDesc{
	ServiceName: "services.Timed",
	HandlerType: (*TimedServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Show",
			Handler:    _Timed_Show_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}

func init() { proto.RegisterFile("services.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x77, 0x65, 0xb7, 0xb8, 0xd3, 0xe2, 0x61, 0xd0, 0x52, 0x3c, 0xd5, 0x9c, 0x7a, 0xea,
	0x61, 0x45, 0x2d, 0x5e, 0x44, 0x28, 0x82, 0xd7, 0xb4, 0xe0, 0x39, 0x76, 0xa7, 0x1a, 0x64, 0x37,
	0x35, 0x99, 0xda, 0xfe, 0x7c, 0x49, 0x76, 0x2d, 0x51, 0xf0, 0xd2, 0xdb, 0x9b, 0xf0, 0xe6, 0x3d,
	0xe6, 0x23, 0x70, 0xe6, 0xc8, 0x7e, 0xe9, 0x15, 0xb9, 0xe9, 0xc6, 0x1a, 0x36, 0x78, 0xfa, 0x33,
	0x8b, 0x2b, 0xe8, 0xcf, 0xad, 0xda, 0x49, 0xfa, 0xdc, 0x92, 0x63, 0x44, 0xc8, 0x2a, 0xc5, 0x6a,
	0x94, 0x8e, 0xd3, 0xc9, 0x40, 0x06, 0x2d, 0xee, 0x61, 0xd0, 0x5a, 0xdc, 0xc6, 0x34, 0x8e, 0xbc,
	0x67, 0x65, 0x2a, 0x0a, 0x9e, 0x5c, 0x06, 0x8d, 0x43, 0xe8, 0x39, 0x56, 0xbc, 0x75, 0xa3, 0x93,
	0x71, 0x3a, 0x29, 0x64, 0x37, 0x89, 0x1b, 0xe8, 0x2f, 0x69, 0xcf, 0x51, 0x3c, 0xd3, 0x9e, 0xc3,
	0x6a, 0x21, 0x83, 0xf6, 0x6f, 0x6b, 0xd3, 0x70, 0xb7, 0x18, 0xb4, 0xaf, 0x6c, 0xd7, 0x8e, 0xa8,
	0x9c, 0x01, 0x2c, 0x75, 0x4d, 0x4f, 0xc6, 0xd6, 0x8a, 0xbd, 0x6b, 0x1d, 0x54, 0xd7, 0xd9, 0x4d,
	0xff, 0xb6, 0xea, 0x9a, 0x8e, 0x69, 0x2d, 0xe7, 0x50, 0x3c, 0xd7, 0xea, 0x8d, 0x16, 0xba, 0xf9,
	0xc0, 0x3b, 0xc8, 0x3c, 0x31, 0xbc, 0x98, 0x1e, 0xb8, 0x47, 0x90, 0x2f, 0x87, 0x7f, 0x9f, 0xdb,
	0x3e, 0x91, 0x94, 0x8f, 0x90, 0xfb, 0xbb, 0x2b, 0x9c, 0x41, 0xfe, 0x62, 0x35, 0x53, 0x1c, 0x11,
	0x81, 0x8c, 0x23, 0x62, 0x50, 0x22, 0x29, 0x1f, 0x20, 0xf7, 0x47, 0x54, 0x78, 0x0b, 0xd9, 0xe2,
	0xdd, 0xec, 0xf0, 0x3c, 0xb2, 0x1e, 0xb8, 0xfc, 0x0a, 0x88, 0x6e, 0x16, 0xc9, 0x6b, 0x2f, 0x7c,
	0x91, 0xeb, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x75, 0xc4, 0x35, 0xaa, 0x34, 0x02, 0x00, 0x00,
}
