[dspd]
grpc_address="localhost:20000"

[textd]
grpc_address="localhost:20001"
owm_token=":owm_token:"
font_path="/usr/share/develed/fonts"
datetime_font="font4x8"
bitdatetime_font="fontbit5x9"
temperature_font="font4x8"
simboli_font="font5x7"
show_second=false
date_stay_time=10 #second
text_stay_time=60 #second
text_scroll_time=100 #millisecond

[[bitmapfont]]
name="font5x7"
filename="font5x7.png"
high=7
width=5

[[bitmapfont]]
name="font4x9"
filename="font4x9.png"
high=9
width=4

[[bitmapfont]]
name="font4x8"
filename="font4x8.png"
high=8
width=4

[[bitmapfont]]
name="fontbit5x9"
filename="fontbit5x9.png"
high=9
width=5

[imaged]
grpc_address="localhost:20002"

[bot]
slack_token=":slack_bot_token:"

