[dspd]
grpc_address="localhost:20000"

[textd]
grpc_address="localhost:20001"
font_path="/usr/share/develed/fonts"
datetime_font=""
show_second=false
date_stay_time=10 #second
text_stay_time=60 #second
text_scroll_time=100 #millisecond

[[bitmapfont]]
name="font5x7"
filename="font5x7.png"
high=7
width=5

[[bitmapfont]]
name="font6x8"
filename="font6x8.png"
high=6
width=8

[imaged]
grpc_address="localhost:20002"

[bot]
slack_token=":slack_bot_token:"

