[dspd]
grpc_address="localhost:20000"

[textd]
grpc_address="localhost:20001"
priority=0 #0 Minor, 10 Max
font_path="resources/fonts"
datetime_font="font4x8"
show_second=false
date_stay_time=10 #second
text_stay_time=60 #second
text_scroll_time=100 #millisecond

[[bitmapfont]]
name="font5x7"
filename="font5x7.png"
high=7
width=5

[[bitmapfont]]
name="font4x8"
filename="font4x8.png"
high=8
width=4

[imaged]
grpc_address="localhost:20002"
priority=1 #0 Minor, 10 Max

[bot]
slack_token=":slack_bot_token:"

