[dspd]
grpc_address="localhost:20000"

[textd]
grpc_address="localhost:20001"
font_path="/usr/share/develed/fonts"

[[bitmapfont]]
name="font5x7"
filename="font5x7.png"
high=7
width=5

[[bitmapfont]]
name="font6x8"
filename="font6x8.png"
high=6
width=8

[bot]
slack_token=":slack_bot_token:"

